[default]
DEBUG = false
EXTENSIONS = [
    "sala_de_estudos_flask.ext.db:init_app",
    "sala_de_estudos_flask.ext.migrate:init_app",
    "sala_de_estudos_flask.ext.cli:init_app",
#    "sala_de_estudos_flask.ext.admin:init_app",
    "sala_de_estudos_flask.ext.api:init_app"
]
SQLALCHEMY_TRACK_MODIFICATIONS = false
FLASK_ADMIN_SWATCH = "paper"
ADMIN_NAME = "Sala de Estudos Admin"
JSON_AS_ASCII = false

[development]
DEBUG = true
ADMIN_NAME="Sala de Estudos Admin Development"

[test]
