[default]
DEBUG = false
EXTENSIONS = [
    "sala_de_estudos_flask.ext.db:init_app",
    "sala_de_estudos_flask.ext.migrate:init_app",
    "sala_de_estudos_flask.ext.cli:init_app"
]
SQLALCHEMY_TRACK_MODIFICATIONS = false

[development]
DEBUG = true

[test]
